name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-virtualenv git zip unzip openjdk-11-jdk
          pip install --upgrade pip
          pip install buildozer cython kivy requests

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: device-tracker-client-apk
          path: bin/*.apk
